# Generated by Django 2.0.3 on 2019-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='reading',
            field=models.CharField(max_length=255),
        ),
    ]
