# Generated by Django 2.1.8 on 2019-05-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0002_auto_20190518_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='dateRead',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
