# Generated by Django 2.1.8 on 2019-05-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0004_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRead', models.CharField(max_length=255, unique=True)),
                ('reading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRead', models.CharField(max_length=255, unique=True)),
                ('reading', models.CharField(max_length=255)),
            ],
        ),
    ]
