# Generated by Django 2.1.8 on 2019-05-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0005_light_motion'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('DataMessageGUID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('SensorID', models.CharField(max_length=7)),
                ('MessageDate', models.CharField(max_length=200)),
                ('State', models.IntegerField(max_length=4)),
                ('SignalStrength', models.IntegerField(max_length=4)),
                ('Voltage', models.CharField(max_length=255)),
                ('Battery', models.IntegerField(max_length=4)),
                ('Data', models.CharField(max_length=255)),
                ('DisplayData', models.CharField(max_length=255)),
                ('PlotValue', models.CharField(max_length=255)),
                ('MetNotificationRequirements', models.CharField(max_length=35)),
                ('GatewayID', models.CharField(max_length=7)),
                ('DataValues', models.CharField(max_length=255)),
                ('DataTypes', models.CharField(max_length=255)),
                ('PlotValues', models.CharField(max_length=255)),
                ('PlotLabels', models.CharField(max_length=255)),
            ],
        ),
    ]
