# Generated by Django 2.1.8 on 2019-05-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0007_auto_20190529_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sensorData',
            new_name='Sensor',
        ),
    ]
