# Generated by Django 2.1.8 on 2019-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0008_auto_20190530_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='MessageDate',
            field=models.DateTimeField(),
        ),
    ]
