# Generated by Django 2.1.8 on 2019-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monnit', '0010_vibration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='dateRead',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='dateRead',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='dateRead',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='dateRead',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='vibration',
            name='dateRead',
            field=models.DateTimeField(unique=True),
        ),
    ]
